import { createContext, useContext, useState, ReactNode } from "react";

type LanguageCode = "es" | "en";

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("es");

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    // Return the value if it exists (including empty strings), otherwise return the key
    return value !== undefined ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

const translations: Record<LanguageCode, any> = {
  es: {
    header: {
      inicio: "Inicio",
      proyectos: "Proyectos",
      calculadora: "Calculadora de financiamiento",
      financiamiento: "Financiamiento",
      contacto: "Contacto",
      hablarAhora: "Hablar Ahora",
    },
    hero: {
      title:
        "Proyectos Inmobiliarios en las mejores locaciones de la Zona Norte de Costa Rica.",
      subtitle: "Financiamiento Sin Prima Ni Fiador.",
      description:
        "Creamos proyectos sostenibles con alto potencial de crecimiento. Financiamos al 100% — sin prima, sin fiador y sin estudio crediticio. Impulsamos inversiones seguras y proyectos que transforman la región.",
      description1:
        "Creamos proyectos sostenibles, con alto potencial de crecimiento.",
      financing:
        "💰 Financiamos al 100% — sin prima, sin fiador y sin estudio crediticio.",
      description2:
        "Impulsamos inversiones seguras y proyectos que transforman la región.",
      cta: "Nuestros Proyectos",
    },
    projects: {
      title: "Nuestros Proyectos",
      subtitle:
        "Inversiones únicas en las zonas más privilegiadas del norte de Costa Rica",
      rioCeleste: {
        title: "Río Celeste Oasis",
        location: "Katira, Guatuso · Zona Norte, Alajuela",
        price: "",
        size: "Desde 1.300 m² hasta 5.000 m²",
        features: [
          "Acceso privado y directo al Río Celeste",
          "15 quintas de 5.000 m² + lotes desde 1.300 m²",
          "Seguridad: control de acceso",
          "Ranchos BBQ, baños, senderos y deck",
        ],
        badges: ["Disponible", "Acceso privado al río", "Balneario natural"],
        description:
          "El Río Celeste es famoso por su color turquesa único en el mundo. Ofrecemos lotes de 1300m2 y 5000m2 desde los $30 y los $45 por m2, con acceso directo al río, privacidad total y un potencial extraordinario para Airbnb, glamping o finca de retiro.",
        viewDetails: "Ver detalles",
      },
      llanadaViews: {
        title: "Lomas De La Llanada",
        location: "Ciudad Quesada, San Carlos",
        price: "",
        size: "Lotes desde 600 m² hasta 5,000 m²",
        features: [
          "Vistas panorámicas espectaculares",
          "Cerca de la ciudad y todos los servicios",
          "Clima único de montaña",
          "Zona con Plan Regulador activo",
        ],
        badges: ["Premium", "Vistas Espectaculares", "Cerca de todo"],
        description:
          "Ubicado en Ciudad Quesada con vistas panorámicas, clima único y ubicación estratégica. Lotes desde ₡45,000/m² (600 m²) hasta ₡13,000/m² (5,000 m²). Zona con planificación activa y desarrollo sostenible.",
        viewDetails: "Ver detalles",
      },
      financingDetails: [
        "Financiamiento al 100% sin prima",
        "Sin fiador ni estudio crediticio",
        "Trámite sencillo",
        "Mejores condiciones del mercado",
      ],
    },
    calculator: {
      title: "Calculadora de Financiamiento",
      subtitle:
        "Calcula tu cuota mensual y descubre lo accesible que es invertir en tu propiedad",
      financingData: "Datos del financiamiento",
      currency: "Moneda",
      lotValue: "Valor del Lote (USD)",
      lotValueCRC: "Valor del Lote (CRC)",
      term: "Plazo (años)",
      selectTerm: "Seleccionar plazo",
      years: "años",
      rate: "Tasa Anual (%)",
      rateUSD: "Tasa de interés en USD: 9% anual",
      rateCRC: "Tasa de interés en Colones: 8% anual",
      calculate: "Calcular",
      monthlyPayment: "Cuota Mensual",
      totalPayment: "Monto Total",
      totalInterest: "Intereses Totales",
      downPaymentRequired: "Prima requerida",
      disclaimer: "Sin fiador. Sin estudio crediticio. Sujeto a disponibilidad del proyecto.",
      cta: "Quiero este financiamiento",
      perMonth: "mes",
    },
    financing: {
      badge: "Inversión Inteligente",
      title: "Financiamiento del 100%",
      subtitle:
        "Sin prima, sin bancos, sin fiador. Elegís el lote, activamos el plan y empezás a invertir sin trámites bancarios ni papeleo eterno.",
      highlight: "✨ Ofrecemos las mejores condiciones del mercado ✨",
      noPrima: "Sin Prima",
      noPrimaDesc: "Comienza tu inversión sin necesidad de pago inicial",
      noBanks: "Sin Bancos, Sin Fiador",
      noBanksDesc:
        "Proceso directo sin trámites bancarios ni papeleo eterno",
      requirements: "Requisitos Mínimos",
      requirementsDesc: "Solo cédula de identidad y visión",
      conditionsTitle: "Las Mejores Condiciones del Mercado",
      bestRates: "Tasas Competitivas",
      bestRatesDesc: "Tasas de interés justas y transparentes, diseñadas para tu éxito",
      flexibility: "Flexibilidad Total",
      flexibilityDesc: "Plazos adaptables a tus necesidades, desde 2 hasta 10 años",
      transparency: "Transparencia Absoluta",
      transparencyDesc: "Sin costos ocultos ni sorpresas. Todo claro desde el inicio",
      cta: "Quiero mi aprobación",
      ctaSubtext: "Respuesta en menos de 24 horas",
    },
    contact: {
      title: "Contáctanos",
      subtitle: "Estamos aquí para responder todas tus preguntas",
      info: "Información de Contacto",
      phone: "Teléfono",
      email: "Email",
      location: "Ubicación",
      locationValue: "Norte de Costa Rica",
      form: {
        name: "Nombre Completo",
        namePlaceholder: "Tu nombre",
        email: "Correo Electrónico",
        emailPlaceholder: "tu@email.com",
        phone: "Teléfono",
        phonePlaceholder: "+506 1234 5678",
        message: "Mensaje",
        messagePlaceholder: "¿En qué podemos ayudarte?",
        submit: "Enviar Mensaje",
      },
    },
    footer: {
      brand: "Eco Viva",
      brandAccent: "Desarrollos",
      tagline: "Desarrollos de lujo en armonía con la naturaleza costarricense",
      quickLinks: "Enlaces Rápidos",
      inicio: "Inicio",
      proyectos: "Proyectos",
      financiamiento: "Financiamiento",
      contacto: "Contacto",
      contactTitle: "Contacto",
      whatsapp: "WhatsApp",
      copyright: "© 2025 Eco Viva Desarrollos. Todos los derechos reservados.",
    },
    survey: {
      title: "Encuesta",
      subtitle: "Ayúdanos a conocerte mejor para ofrecerte la mejor experiencia.",
    },
    financingBanner: {
      headline: "Financiamiento del 100%",
      subheadline: "Solo con tu cédula hacemos el estudio. Sin prima, sin fiador.",
      noPrima: "Sin prima",
      noFiador: "Sin fiador",
      soloCedula: "Solo con cédula",
      cta: "Aplicar ahora",
    },
    booking: {
      badge: "Agenda tu visita",
      heroTitle: "Conoce tu futuro hogar en Costa Rica",
      heroSubtitle: "Agenda una visita guiada a nuestros proyectos y descubre por qué cientos de familias ya eligieron invertir con Eco Viva Desarrollos.",
      location: "Zona Norte, Costa Rica",
      available: "Visitas disponibles todos los días",
      whySchedule: "¿Por qué agendar una visita?",
      whyScheduleDesc: "Una visita presencial te permite conocer de primera mano la calidad de nuestros desarrollos, las vistas impresionantes y el potencial de inversión.",
      benefit1: "Recorrido personalizado por los proyectos",
      benefit2: "Asesoría financiera sin compromiso",
      benefit3: "Conoce las amenidades en persona",
      benefit4: "Explora los lotes disponibles",
      preferDirect: "¿Prefieres contacto directo?",
      preferDirectDesc: "Nuestro equipo está disponible para atenderte por WhatsApp y coordinar tu visita de forma inmediata.",
      contactWhatsApp: "Contactar por WhatsApp",
      selectDateTime: "Selecciona fecha y hora",
      selectDateTimeDesc: "Elige el momento ideal para tu visita",
      readyNext: "¿Listo para dar el siguiente paso?",
      readyNextDesc: "Agenda tu visita hoy y descubre por qué Costa Rica es el destino ideal para tu inversión en bienes raíces.",
      scheduleNow: "Agendar ahora",
    },
    rioCelesteDetail: {
      heroTitle: "Río Celeste Oasis",
      heroSubtitle: "Balneario Natural Privado · Quintas y Lotes Exclusivos",
      heroDescription: "Un proyecto inmobiliario único con acceso privado y directo al Río Celeste, diseñado como un balneario natural de baja densidad en una de las zonas turísticas con mayor proyección de crecimiento en Costa Rica.",
      requestInfo: "Solicitar información",
      scheduleVisit: "Agendar visita",
      galleryTitle: "Galería del proyecto",
      gallerySubtitle: "Naturaleza, río y amenidades del balneario natural.",
      differentProject: "Un proyecto diferente a todo lo demás en la zona",
      differentProjectDesc: "Río Celeste Oasis no es una lotificación tradicional. Es un desarrollo concebido como un balneario natural privado, donde la baja densidad, la privacidad y el acceso directo al río crean un entorno exclusivo, escaso y altamente atractivo para inversión turística, retiro o segunda residencia.",
      investmentOptions: "Opciones de inversión dentro del proyecto",
      investmentOption1: "15 quintas exclusivas de 5.000 m²",
      investmentOption2: "Lotes frente a calle desde 1.300 m²",
      investmentOption3: "Ingreso flexible según perfil de inversión",
      investmentOption4: "Ideal para villas privadas, Airbnb premium, glamping o fincas de retiro",
      riverAccessTitle: "Acceso privado y directo al Río Celeste",
      riverAccessDesc: "Cada propiedad cuenta con acceso privado al río. El Río Celeste no es un atractivo cercano: es parte integral del proyecto, permitiendo experiencias de descanso, recreación, bienestar y contacto directo con la naturaleza.",
      naturalResortTitle: "Concepto de balneario natural",
      commonAreasTitle: "Áreas comunes del proyecto",
      commonArea1: "Ranchos BBQ totalmente equipados",
      commonArea2: "Baños comunes modernos y funcionales",
      commonArea3: "Senderos naturales internos",
      commonArea4: "Deck para yoga, meditación y actividades",
      commonArea5: "Zonas de descanso y contemplación",
      securityTitle: "Seguridad, privacidad y control",
      security1: "Acceso controlado al proyecto",
      security2: "Cámaras de seguridad en puntos estratégicos",
      security3: "Ambiente rural, privado y de baja densidad",
      security4: "Diseñado para tranquilidad de propietarios y huéspedes",
      locationTitle: "Ubicación estratégica y alto potencial de crecimiento",
      locationDesc: "Ubicado en Katira de Guatuso, Alajuela, con conectividad directa por la Ruta Nacional 4 y cercanía a los principales polos de turismo de naturaleza de la Zona Norte. Esta región ha sido identificada por el Instituto Costarricense de Turismo como una de las zonas con mayor proyección de crecimiento turístico del país.",
      targetTitle: "¿Para quién es Río Celeste Oasis?",
      targetInvestor: "Inversionista turístico",
      targetInvestorDesc: "Rentas cortas, glamping y villas boutique con alto atractivo natural.",
      targetPatrimonial: "Comprador patrimonial",
      targetPatrimonialDesc: "Tierra escasa, acceso al río y proyección de plusvalía.",
      targetLifestyle: "Comprador lifestyle",
      targetLifestyleDesc: "Retiro, segunda residencia y conexión con la naturaleza.",
      summaryTitle: "Resumen de valor del proyecto",
      summary1: "Lotes desde 1.300 m² hasta 5.000 m²",
      summary2: "15 quintas exclusivas",
      summary3: "Acceso privado al Río Celeste",
      summary4: "Concepto de balneario natural",
      summary5: "Áreas comunes completas",
      summary6: "Seguridad y control de acceso",
      summary7: "Zona de alto crecimiento turístico",
      summary8: "Proyecto único en su categoría",
      ctaTitle: "Una inversión donde la naturaleza es el activo",
      ctaDesc: "Río Celeste Oasis representa una oportunidad única de inversión en tierra escasa, con alto potencial turístico y un entorno natural que no se puede replicar.",
      pricingTitle: "Opciones de lotes disponibles",
      smallLotsStarting: "Desde 1,300 m²",
      smallLotsTitle: "Lotes pequeños desde 1,300 m²",
      largeLotsStarting: "Desde 5,000 m²",
      largeLotsTitle: "Lotes grandes desde 5,000 m²",
      perSquareMeter: "por metro cuadrado",
      investmentOpportunity: "Oportunidad de Inversión",
      mapTitle: "Oasis Río Celeste – Distribución de Lotes",
      mapSubtitle: "Lotes disponibles con precios aproximados según tamaño",
      availableLots: "Lotes Disponibles",
      lotsAvailable: "Lotes disponibles",
      minimumSize: "Tamaño mínimo",
      maximumSize: "Tamaño máximo",
      from: "Desde",
      priceNote: "Nota:",
      priceNoteText: "Los precios son aproximados y pueden variar según condiciones específicas del lote.",
      noAvailable: "No Disponible",
      viewPlan: "Ver Plano",
    },
    lomasLlanadaDetail: {
      heroTitle: "Lomas de la Llanada",
      heroSubtitle: "Vistas Espectaculares · Ciudad Quesada, San Carlos",
      heroDescription: "Un proyecto inmobiliario con vistas panorámicas, clima único y ubicación estratégica en el corazón de Ciudad Quesada. Lotes desde 600 m² hasta 5,000 m² en una zona con planificación activa y desarrollo sostenible.",
      requestInfo: "Solicitar información",
      scheduleVisit: "Agendar visita",
      downloadInfo: "Descarga información general",
      videoTitle: "Conoce Lomas de la Llanada",
      videoSubtitle: "Descubre las vistas y el entorno único de este proyecto",
      galleryTitle: "Galería del proyecto",
      gallerySubtitle: "Vistas panorámicas y entorno natural de Lomas de la Llanada",
      differentProject: "Un proyecto en el corazón de la ciudad con visión de futuro",
      differentProjectDesc: "Lomas de la Llanada forma parte de un entorno con visión, planificación y respaldo institucional. No es solo un proyecto rodeado de naturaleza, sino una inversión dentro de una ciudad que crece con orden, participación comunitaria y enfoque sostenible.",
      videoFeature1: "Recorrido aéreo del proyecto",
      videoFeature2: "Vistas panorámicas reales",
      videoFeature3: "Naturaleza y tranquilidad garantizadas",
      pricingTitle: "Opciones de lotes disponibles",
      startingPrice: "Desde 600 m²",
      price600Title: "Lotes desde 600 m²",
      perSquareMeter: "por metro cuadrado",
      price600Desc: "Ideales para construcción de vivienda familiar. Ubicados a orilla de calle con fácil acceso.",
      premiumView: "Vista Panorámica",
      price5000ViewTitle: "Lotes de 5,000 m² con vista",
      price5000ViewDesc: "Lotes premium con vistas panorámicas espectaculares a Ciudad Quesada y el Volcán Arenal.",
      bestValue: "Mejor valor",
      price5000Title: "Lotes de 5,000 m² sin vista",
      price5000Desc: "Amplios lotes a excelente precio para desarrollo residencial o agrícola.",
      strategicLocationTitle: "Ubicación dentro de un distrito con planificación activa",
      strategicLocationDesc: "Lomas de la Llanada se ubica en Ciudad Quesada, el distrito central del cantón de San Carlos, una zona que cuenta con un Plan Regulador moderno que garantiza crecimiento ordenado, usos de suelo compatibles y desarrollo sostenible a largo plazo.",
      keyFeaturesTitle: "¿Por qué invertir en Lomas de la Llanada?",
      feature1Title: "Planificación activa",
      feature1Desc: "Ubicado en un distrito con Plan Regulador moderno que garantiza crecimiento ordenado y desarrollo sostenible.",
      feature2Title: "Armonía con la naturaleza",
      feature2Desc: "El Plan Regulador prioriza un modelo de desarrollo equilibrado con el entorno natural, protegiendo la plusvalía.",
      feature3Title: "Gobernanza participativa",
      feature3Desc: "Ciudad Quesada cuenta con un modelo de gobernanza territorial participativa que brinda seguridad para la inversión.",
      feature4Title: "Visión urbana moderna",
      feature4Desc: "Mejoras futuras en movilidad como infraestructura peatonal, ciclovías y soluciones urbanas modernas.",
      feature5Title: "Espacios públicos",
      feature5Desc: "Sólida red de parques, zonas verdes, plazas públicas y áreas comunales cerca del proyecto.",
      feature6Title: "Servicios consolidados",
      feature6Desc: "Cerca de mercado municipal, biblioteca, centros administrativos y comercio activo.",
      urbanVisionTitle: "Visión urbana moderna y funcional",
      urbanVision1: "Infraestructura peatonal y ciclovías proyectadas",
      urbanVision2: "Ciudad más accesible, ordenada y centrada en las personas",
      urbanVision3: "Reducción de impactos negativos como ruido y congestión",
      urbanVision4: "Usos de suelo compatibles con residencia de calidad",
      servicesTitle: "Infraestructura de servicios consolidados",
      service1: "Mercado municipal cercano",
      service2: "Biblioteca y centros administrativos",
      service3: "Comercio activo y servicios esenciales",
      service4: "Acceso a hospitales y centros de salud",
      connectivityTitle: "Conectividad y base para crecimiento futuro",
      connectivityDesc: "El distrito cuenta con una red vial inventariada y terrenos estratégicos destinados al crecimiento ordenado, lo que asegura conectividad, acceso y proyección de desarrollo a mediano y largo plazo.",
      targetTitle: "¿Para quién es Lomas de la Llanada?",
      targetFamily: "Familias jóvenes",
      targetFamilyDesc: "Ambiente tranquilo, cerca de servicios y escuelas, con espacio para crecer.",
      targetInvestor: "Inversionista patrimonial",
      targetInvestorDesc: "Tierra con alto potencial de plusvalía en zona de crecimiento planificado.",
      targetRetiree: "Jubilados y retirados",
      targetRetireeDesc: "Clima único, vistas espectaculares y cercanía a servicios de salud.",
      summaryTitle: "Resumen de valor del proyecto",
      summary1: "Lotes desde 600 m² hasta 5,000 m²",
      summary2: "Vistas panorámicas espectaculares",
      summary3: "Cerca de la ciudad y todos los servicios",
      summary4: "Clima único de montaña",
      summary5: "Zona con Plan Regulador activo",
      summary6: "Alta proyección de plusvalía",
      summary7: "Gobernanza participativa",
      summary8: "Desarrollo sostenible garantizado",
      ctaTitle: "Una inversión con visión, planificación y respaldo",
      ctaDesc: "Lomas de la Llanada no es solo un proyecto rodeado de naturaleza, sino una inversión dentro de una ciudad que crece con orden, participación comunitiva y enfoque sostenible.",
      availableLots: "Lotes Disponibles",
      lotsAvailable: "Lotes disponibles",
      minimumSize: "Tamaño mínimo",
      maximumSize: "Tamaño máximo",
      from: "Desde",
      smallLotsTitle: "¿Buscas algo más pequeño?",
      smallLotsDesc: "También ofrecemos lotes más compactos de entre 690 y 1.300 m², ideales para quienes desean una opción más accesible dentro del mismo proyecto. Estos lotes están ubicados frente a calle pública, por lo que no cuentan con acceso privado como los lotes del bloque principal. La gran ventaja es que están completamente listos para construir: ya cuentan con agua potable y electricidad instalada. El financiamiento para estos lotes requiere una prima del 25%.",
      smallLotsFeature1: "Lotes de 690 a 1.300 m²",
      smallLotsFeature2: "Frente a calle pública",
      smallLotsFeature3: "Agua y electricidad instaladas",
      smallLotsFeature4: "Listos para construir",
      smallLotsFeature5: "Prima del 25% para financiamiento",
      smallLotsDownload: "Descargar información completa",
    },
  },
  en: {
    header: {
      inicio: "Home",
      proyectos: "Projects",
      calculadora: "Financing Calculator",
      financiamiento: "Financing",
      contacto: "Contact",
      hablarAhora: "Talk Now",
    },
    hero: {
      title:
        "Real Estate Projects in the best locations of Northern Costa Rica.",
      subtitle:
        "Financing With Immediate Approval Without Down Payment or Guarantor.",
      description:
        "We create sustainable projects with high growth potential. 100% financing — no down payment, no guarantor, and no credit check. We promote safe investments and projects that transform the region.",
      description1:
        "We create sustainable projects with high growth potential.",
      financing:
        "💰 100% financing — no down payment, no guarantor, and no credit check.",
      description2:
        "We promote safe investments and projects that transform the region.",
      cta: "Our Projects",
    },
    projects: {
      title: "Our Projects",
      subtitle:
        "Unique investments in the most privileged areas of northern Costa Rica",
      rioCeleste: {
        title: "Río Celeste Oasis",
        location: "Katira, Guatuso · North Zone, Alajuela",
        price: "",
        size: "From 1,300 m² to 5,000 m²",
        features: [
          "Private and direct access to Río Celeste",
          "15 quintas of 5,000 m² + lots from 1,300 m²",
          "Security: access control + cameras",
          "BBQ ranches, bathrooms, trails and deck",
        ],
        badges: ["Available", "Private river access", "Natural resort"],
        description:
          "Within the Tenorio Volcano National Park area, Rio Celeste is famous for its unique turquoise color in the world. In this project, each quinta offers 5,000 m² for $150,000 USD, that is, $30 per m², with direct river access, total privacy and extraordinary potential for Airbnb, glamping or retreat farm.",
        viewDetails: "View details",
      },
      llanadaViews: {
        title: "Lomas De La Llanada",
        location: "Ciudad Quesada, San Carlos",
        price: "",
        size: "Lots from 600 m² to 5,000 m²",
        features: [
          "Spectacular panoramic views",
          "Close to city and all services",
          "Unique mountain climate",
          "Area with active Regulatory Plan",
        ],
        badges: ["Premium", "Spectacular Views", "Close to Everything"],
        description:
          "Located in Ciudad Quesada with panoramic views, unique climate and strategic location. Lots from ₡45,000/m² (600 m²) to ₡13,000/m² (5,000 m²). Area with active planning and sustainable development.",
        viewDetails: "View details",
      },
      financingDetails: [
        "100% financing without down payment",
        "No guarantor or credit check",
        "Immediate approval",
        "Best market conditions",
      ],
    },
    calculator: {
      title: "Financing Calculator",
      subtitle:
        "Calculate your monthly payment and discover how affordable it is to invest in your property",
      financingData: "Financing Details",
      currency: "Currency",
      lotValue: "Lot Value (USD)",
      lotValueCRC: "Lot Value (CRC)",
      term: "Term (years)",
      selectTerm: "Select term",
      years: "years",
      rate: "Annual Rate (%)",
      rateUSD: "Interest rate in USD: 9% annual",
      rateCRC: "Interest rate in Colones: 8% annual",
      calculate: "Calculate",
      monthlyPayment: "Monthly Payment",
      totalPayment: "Total Amount",
      totalInterest: "Total Interest",
      downPaymentRequired: "Down payment required",
      disclaimer: "Immediate approval. No guarantor. No credit check. Subject to project availability.",
      cta: "I want this financing",
      perMonth: "month",
    },
    financing: {
      badge: "Smart Investment",
      title: "100% Financing",
      subtitle:
        "No down payment, no banks, no guarantor. You choose the lot, we activate the plan and you start investing without bank procedures or endless paperwork.",
      highlight: "✨ We offer the best market conditions ✨",
      noPrima: "No Down Payment",
      noPrimaDesc:
        "Start your investment without the need for an initial payment",
      noBanks: "No Banks, No Guarantor",
      noBanksDesc:
        "Direct process without bank procedures or endless paperwork",
      requirements: "Minimal Requirements",
      requirementsDesc: "Only ID and visa required",
      conditionsTitle: "The Best Market Conditions",
      bestRates: "Competitive Rates",
      bestRatesDesc: "Fair and transparent interest rates, designed for your success",
      flexibility: "Total Flexibility",
      flexibilityDesc: "Payment terms adaptable to your needs, from 2 to 10 years",
      transparency: "Absolute Transparency",
      transparencyDesc: "No hidden costs or surprises. Everything clear from the start",
      cta: "I want my approval",
      ctaSubtext: "Response in less than 24 hours",
    },
    contact: {
      title: "Contact Us",
      subtitle: "We are here to answer all your questions",
      info: "Contact Information",
      phone: "Phone",
      email: "Email",
      location: "Location",
      locationValue: "Northern Costa Rica",
      form: {
        name: "Full Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "your@email.com",
        phone: "Phone",
        phonePlaceholder: "+506 1234 5678",
        message: "Message",
        messagePlaceholder: "How can we help you?",
        submit: "Send Message",
      },
    },
    footer: {
      brand: "Eco Viva",
      brandAccent: "Desarrollos",
      tagline: "Luxury developments in harmony with Costa Rican nature",
      quickLinks: "Quick Links",
      inicio: "Home",
      proyectos: "Projects",
      financiamiento: "Financing",
      contacto: "Contact",
      contactTitle: "Contact",
      whatsapp: "WhatsApp",
      copyright: "© 2025 Eco Viva Desarrollos. All rights reserved.",
    },
    survey: {
      title: "Survey",
      subtitle: "Help us get to know you better to offer you the best experience.",
    },
    financingBanner: {
      headline: "We finance 100% of the land!",
      subheadline: "Only with your ID we do the study. No down payment, no guarantor.",
      noPrima: "No down payment",
      noFiador: "No guarantor",
      soloCedula: "Only ID required",
      cta: "Apply now",
    },
    booking: {
      badge: "Schedule your visit",
      heroTitle: "Discover your future home in Costa Rica",
      heroSubtitle: "Schedule a guided tour of our projects and discover why hundreds of families have already chosen to invest with Eco Viva Desarrollos.",
      location: "Northern Zone, Costa Rica",
      available: "Visits available every day",
      whySchedule: "Why schedule a visit?",
      whyScheduleDesc: "An in-person visit allows you to experience firsthand the quality of our developments, the impressive views and the investment potential.",
      benefit1: "Personalized tour of the projects",
      benefit2: "No-obligation financial advice",
      benefit3: "See the amenities in person",
      benefit4: "Explore the available lots",
      preferDirect: "Prefer direct contact?",
      preferDirectDesc: "Our team is available to assist you via WhatsApp and coordinate your visit immediately.",
      contactWhatsApp: "Contact via WhatsApp",
      selectDateTime: "Select date and time",
      selectDateTimeDesc: "Choose the ideal time for your visit",
      readyNext: "Ready to take the next step?",
      readyNextDesc: "Schedule your visit today and discover why Costa Rica is the ideal destination for your real estate investment.",
      scheduleNow: "Schedule now",
    },
    rioCelesteDetail: {
      heroTitle: "Río Celeste Oasis",
      heroSubtitle: "Private Natural Resort · Exclusive Quintas and Lots",
      heroDescription: "A unique real estate project with private and direct access to Río Celeste, designed as a low-density natural resort in one of the tourist areas with the highest growth projection in Costa Rica.",
      requestInfo: "Request information",
      scheduleVisit: "Schedule visit",
      galleryTitle: "Project Gallery",
      gallerySubtitle: "Nature, river and amenities of the natural resort.",
      differentProject: "A project different from everything else in the area",
      differentProjectDesc: "Río Celeste Oasis is not a traditional subdivision. It is a development conceived as a private natural resort, where low density, privacy and direct river access create an exclusive, scarce and highly attractive environment for tourist investment, retreat or second residence.",
      investmentOptions: "Investment options within the project",
      investmentOption1: "15 exclusive quintas of 5,000 m²",
      investmentOption2: "Street-front lots from 1,300 m²",
      investmentOption3: "Flexible entry according to investment profile",
      investmentOption4: "Ideal for private villas, premium Airbnb, glamping or retreat farms",
      riverAccessTitle: "Private and direct access to Río Celeste",
      riverAccessDesc: "Each property has private access to the river. Río Celeste is not a nearby attraction: it is an integral part of the project, allowing experiences of rest, recreation, wellness and direct contact with nature.",
      naturalResortTitle: "Natural resort concept",
      commonAreasTitle: "Project common areas",
      commonArea1: "Fully equipped BBQ ranches",
      commonArea2: "Modern and functional common bathrooms",
      commonArea3: "Internal nature trails",
      commonArea4: "Deck for yoga, meditation and activities",
      commonArea5: "Rest and contemplation areas",
      securityTitle: "Security, privacy and control",
      security1: "Controlled access to the project",
      security2: "Security cameras at strategic points",
      security3: "Rural, private and low-density environment",
      security4: "Designed for the tranquility of owners and guests",
      locationTitle: "Strategic location and high growth potential",
      locationDesc: "Located in Katira de Guatuso, Alajuela, with direct connectivity via National Route 4 and proximity to the main nature tourism hubs in the Northern Zone. This region has been identified by the Costa Rican Tourism Institute as one of the areas with the highest tourism growth projection in the country.",
      targetTitle: "Who is Río Celeste Oasis for?",
      targetInvestor: "Tourist investor",
      targetInvestorDesc: "Short-term rentals, glamping and boutique villas with high natural appeal.",
      targetPatrimonial: "Patrimonial buyer",
      targetPatrimonialDesc: "Scarce land, river access and capital appreciation projection.",
      targetLifestyle: "Lifestyle buyer",
      targetLifestyleDesc: "Retreat, second residence and connection with nature.",
      summaryTitle: "Project value summary",
      summary1: "Lots from 1,300 m² to 5,000 m²",
      summary2: "15 exclusive quintas",
      summary3: "Private access to Río Celeste",
      summary4: "Natural resort concept",
      summary5: "Complete common areas",
      summary6: "Security and access control",
      summary7: "High tourist growth area",
      summary8: "Unique project in its category",
      ctaTitle: "An investment where nature is the asset",
      ctaDesc: "Río Celeste Oasis represents a unique investment opportunity in scarce land, with high tourist potential and a natural environment that cannot be replicated.",
      pricingTitle: "Available lot options",
      smallLotsStarting: "From 1,300 m²",
      smallLotsTitle: "Small lots from 1,300 m²",
      largeLotsStarting: "From 5,000 m²",
      largeLotsTitle: "Large lots from 5,000 m²",
      perSquareMeter: "per square meter",
      investmentOpportunity: "Investment Opportunity",
      mapTitle: "Oasis Río Celeste – Lot Distribution",
      mapSubtitle: "Available lots with approximate prices by size",
      availableLots: "Available Lots",
      lotsAvailable: "Lots available",
      minimumSize: "Minimum size",
      maximumSize: "Maximum size",
      from: "From",
      priceNote: "Note:",
      priceNoteText: "Prices are approximate and may vary according to specific lot conditions.",
      noAvailable: "Not Available",
      viewPlan: "View Plan",
    },
    lomasLlanadaDetail: {
      heroTitle: "Lomas de la Llanada",
      heroSubtitle: "Spectacular Views · Ciudad Quesada, San Carlos",
      heroDescription: "A real estate project with panoramic views, unique climate and strategic location in the heart of Ciudad Quesada. Lots from 600 m² to 5,000 m² in an area with active planning and sustainable development.",
      requestInfo: "Request information",
      scheduleVisit: "Schedule visit",
      downloadInfo: "Download General Information",
      videoTitle: "Discover Lomas de la Llanada",
      videoSubtitle: "Explore the views and unique environment of this project",
      galleryTitle: "Project Gallery",
      gallerySubtitle: "Panoramic views and natural surroundings of Lomas de la Llanada",
      differentProject: "A project in the heart of the city with a vision for the future",
      differentProjectDesc: "Lomas de la Llanada is part of an environment with vision, planning and institutional support. It is not just a project surrounded by nature, but an investment within a city that grows with order, community participation and a sustainable approach.",
      videoFeature1: "Aerial tour of the project",
      videoFeature2: "Real panoramic views",
      videoFeature3: "Guaranteed nature and tranquility",
      pricingTitle: "Available lot options",
      startingPrice: "From 600 m²",
      price600Title: "Lots from 600 m²",
      perSquareMeter: "per square meter",
      price600Desc: "Ideal for family home construction. Located streetside with easy access.",
      premiumView: "Panoramic View",
      price5000ViewTitle: "5,000 m² lots with view",
      price5000ViewDesc: "Premium lots with spectacular panoramic views of Ciudad Quesada and Arenal Volcano.",
      bestValue: "Best value",
      price5000Title: "5,000 m² lots without view",
      price5000Desc: "Large lots at excellent price for residential or agricultural development.",
      strategicLocationTitle: "Location within a district with active planning",
      strategicLocationDesc: "Lomas de la Llanada is located in Ciudad Quesada, the central district of San Carlos canton, an area with a modern Regulatory Plan that guarantees orderly growth, compatible land uses and long-term sustainable development.",
      keyFeaturesTitle: "Why invest in Lomas de la Llanada?",
      feature1Title: "Active planning",
      feature1Desc: "Located in a district with a modern Regulatory Plan that guarantees orderly growth and sustainable development.",
      feature2Title: "Harmony with nature",
      feature2Desc: "The Regulatory Plan prioritizes a development model balanced with the natural environment, protecting property value.",
      feature3Title: "Participatory governance",
      feature3Desc: "Ciudad Quesada has a participatory territorial governance model that provides security for investment.",
      feature4Title: "Modern urban vision",
      feature4Desc: "Future improvements in mobility such as pedestrian infrastructure, bike paths and modern urban solutions.",
      feature5Title: "Public spaces",
      feature5Desc: "Solid network of parks, green areas, public squares and community areas near the project.",
      feature6Title: "Consolidated services",
      feature6Desc: "Near municipal market, library, administrative centers and active commerce.",
      urbanVisionTitle: "Modern and functional urban vision",
      urbanVision1: "Projected pedestrian infrastructure and bike paths",
      urbanVision2: "More accessible, orderly and people-centered city",
      urbanVision3: "Reduction of negative impacts such as noise and congestion",
      urbanVision4: "Land uses compatible with quality residence",
      servicesTitle: "Consolidated service infrastructure",
      service1: "Nearby municipal market",
      service2: "Library and administrative centers",
      service3: "Active commerce and essential services",
      service4: "Access to hospitals and health centers",
      connectivityTitle: "Connectivity and foundation for future growth",
      connectivityDesc: "The district has an inventoried road network and strategic lands destined for orderly growth, ensuring connectivity, access and development projection in the medium and long term.",
      targetTitle: "Who is Lomas de la Llanada for?",
      targetFamily: "Young families",
      targetFamilyDesc: "Quiet environment, close to services and schools, with room to grow.",
      targetInvestor: "Patrimonial investor",
      targetInvestorDesc: "Land with high appreciation potential in a planned growth area.",
      targetRetiree: "Retirees",
      targetRetireeDesc: "Unique climate, spectacular views and proximity to health services.",
      summaryTitle: "Project value summary",
      summary1: "Lots from 600 m² to 5,000 m²",
      summary2: "Spectacular panoramic views",
      summary3: "Close to the city and all services",
      summary4: "Unique mountain climate",
      summary5: "Area with active Regulatory Plan",
      summary6: "High appreciation projection",
      summary7: "Participatory governance",
      summary8: "Guaranteed sustainable development",
      ctaTitle: "An investment with vision, planning and support",
      ctaDesc: "Lomas de la Llanada is not just a project surrounded by nature, but an investment within a city that grows with order, community participation and a sustainable approach.",
      availableLots: "Available Lots",
      lotsAvailable: "Lots available",
      minimumSize: "Minimum size",
      maximumSize: "Maximum size",
      from: "From",
      smallLotsTitle: "Looking for something smaller?",
      smallLotsDesc: "We also offer more compact lots between 690 and 1,300 m², ideal for those looking for a more accessible option within the same project. These lots face a public road, so they do not have a private entrance like the main block lots. The great advantage is that they are completely ready to build: they already have potable water and electricity installed. Financing for these lots requires a 25% down payment.",
      smallLotsFeature1: "Lots from 690 to 1,300 m²",
      smallLotsFeature2: "Facing public road",
      smallLotsFeature3: "Water and electricity installed",
      smallLotsFeature4: "Ready to build",
      smallLotsFeature5: "25% down payment for financing",
      smallLotsDownload: "Download complete information",
    },
  },
};

